# Generated by Django 2.1.2 on 2018-10-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stashified', '0003_print_release_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='print',
            old_name='release_year',
            new_name='release_date',
        ),
    ]
