# Generated by Django 2.1.2 on 2018-10-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stashified', '0004_auto_20181025_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='release_date',
            field=models.DateField(null=True),
        ),
    ]
