# Generated by Django 2.1.2 on 2018-10-25 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stashified', '0005_auto_20181025_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='style',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bags', to='stashified.Style'),
            preserve_default=False,
        ),
    ]
