# Generated by Django 2.1.2 on 2018-10-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stashified', '0006_bag_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='image',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='print',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
