# Generated by Django 2.1.2 on 2018-12-11 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stashified', '0007_auto_20181025_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='image_resized',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
